# PyTorch, NumPy, and Python Reference Sheet

Runnable companion to the [reference sheet post](https://raila.io/#/blog/pytorch-numpy-python-reference) on [raila.io](https://raila.io). Run each cell (Shift+Enter) and edit freely — this is a scratch copy, changes here don't affect the original.

## Setup

In [52]:
import numpy as np
import torch
import torch.nn as nn

print("numpy", np.__version__, "| torch", torch.__version__)

numpy 2.1.3 | torch 2.11.0+cpu


## Creating Arrays / Tensors

In [59]:
a = np.array([1, 2, 3])
t = torch.tensor([1, 2, 3])

print('Ones matrices:')
print(np.zeros((2, 3)))
print(torch.zeros(2, 3), "\n")

print('Ones matrices:')
print(np.ones((2, 3)))
print(torch.ones(2, 3), "\n")

print('Random matrices:')
print(np.random.rand(2, 3))
print(torch.rand(2, 3), "\n")


print('Identity matrix:')
print(torch.eye(2, 3), "\n") # Accepts maximum 2 dimensions

print('Range 0-10-2:')
print(torch.arange(0, 10, 2), "\n")

print('Evenly spaced 0-1-5:')
print(torch.linspace(0, 1, 5), "\n")

print('Add a new axis:')
print(t.shape)
print(t.unsqueeze(1).shape, "\n")

Ones matrices:
[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Ones matrices:
[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random matrices:
[[0.68261229 0.74871613 0.91884694]
 [0.59732102 0.21838824 0.5827808 ]]
tensor([[0.2524, 0.2659, 0.2975],
        [0.4196, 0.4905, 0.5068]]) 

Identity matrix:
tensor([[1., 0., 0.],
        [0., 1., 0.]]) 

Range 0-10-2:
tensor([0, 2, 4, 6, 8]) 

Evenly spaced 0-1-5:
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]) 

Add a new axis:
torch.Size([3])
torch.Size([3, 1]) 



## Shape, Indexing, and Slicing

In [ ]:
a = np.arange(12).reshape(3, 4)
t = torch.arange(12).reshape(3, 4)

print(a[1:3, :2])
print(t[1:3, :2])
print(t[t > 5])

## Broadcasting

In [ ]:
a = np.arange(3).reshape(3, 1)
b = np.arange(4).reshape(1, 4)
print((a + b).shape)  # (3, 4)

t1 = torch.arange(3).reshape(3, 1)
t2 = torch.arange(4).reshape(1, 4)
print((t1 + t2).shape)  # (3, 4), identical rule

## Math and Reductions

In [ ]:
t = torch.randn(4, 5)
print(t.sum(dim=0))
values, indices = t.max(dim=1)
print(values, indices)
print(torch.softmax(t, dim=-1).sum(dim=-1))  # rows sum to 1

## NumPy ⇄ PyTorch Interop

In [ ]:
a = np.array([1.0, 2.0, 3.0])
t = torch.from_numpy(a)  # shares memory with a
t[0] = 99
print(a)  # mutated too

back = t.detach().cpu().numpy()
print(back)

## Autograd

In [ ]:
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3 * x
y.backward()
print("dy/dx =", x.grad)  # 2x + 3 = 7.0

## A Tiny Model + Training Step

In [ ]:
class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, out_dim),
        )

    def forward(self, x):
        return self.net(x)

model = MLP(10, 16, 2)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()

x = torch.randn(8, 10)
y = torch.randint(0, 2, (8,))

optimizer.zero_grad()
logits = model(x)
loss = loss_fn(logits, y)
loss.backward()
optimizer.step()
print("loss:", loss.item())